# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _rp_hw_profiles_py
else:
    import _rp_hw_profiles_py

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


RP_HP_OK = _rp_hw_profiles_py.RP_HP_OK
RP_HP_EAL = _rp_hw_profiles_py.RP_HP_EAL
RP_HP_EU = _rp_hw_profiles_py.RP_HP_EU
RP_HP_ERE = _rp_hw_profiles_py.RP_HP_ERE
RP_HP_ERM = _rp_hw_profiles_py.RP_HP_ERM
RP_HP_EMU = _rp_hw_profiles_py.RP_HP_EMU
RP_HP_ECI = _rp_hw_profiles_py.RP_HP_ECI
STEM_125_10_v1_0 = _rp_hw_profiles_py.STEM_125_10_v1_0
STEM_125_14_v1_0 = _rp_hw_profiles_py.STEM_125_14_v1_0
STEM_125_14_v1_1 = _rp_hw_profiles_py.STEM_125_14_v1_1
STEM_122_16SDR_v1_0 = _rp_hw_profiles_py.STEM_122_16SDR_v1_0
STEM_122_16SDR_v1_1 = _rp_hw_profiles_py.STEM_122_16SDR_v1_1
STEM_125_14_LN_v1_1 = _rp_hw_profiles_py.STEM_125_14_LN_v1_1
STEM_125_14_Z7020_v1_0 = _rp_hw_profiles_py.STEM_125_14_Z7020_v1_0
STEM_125_14_Z7020_LN_v1_1 = _rp_hw_profiles_py.STEM_125_14_Z7020_LN_v1_1
STEM_125_14_Z7020_4IN_v1_0 = _rp_hw_profiles_py.STEM_125_14_Z7020_4IN_v1_0
STEM_125_14_Z7020_4IN_v1_2 = _rp_hw_profiles_py.STEM_125_14_Z7020_4IN_v1_2
STEM_125_14_Z7020_4IN_v1_3 = _rp_hw_profiles_py.STEM_125_14_Z7020_4IN_v1_3
STEM_250_12_v1_0 = _rp_hw_profiles_py.STEM_250_12_v1_0
STEM_250_12_v1_1 = _rp_hw_profiles_py.STEM_250_12_v1_1
STEM_250_12_v1_2 = _rp_hw_profiles_py.STEM_250_12_v1_2
STEM_250_12_120 = _rp_hw_profiles_py.STEM_250_12_120
STEM_250_12_v1_2a = _rp_hw_profiles_py.STEM_250_12_v1_2a
Z7010 = _rp_hw_profiles_py.Z7010
Z7020 = _rp_hw_profiles_py.Z7020
RP_HP_ADC_GAIN_NORMAL = _rp_hw_profiles_py.RP_HP_ADC_GAIN_NORMAL
RP_HP_ADC_GAIN_HIGH = _rp_hw_profiles_py.RP_HP_ADC_GAIN_HIGH

def rp_HPGetModel():
    return _rp_hw_profiles_py.rp_HPGetModel()

def rp_HPGetModelName():
    return _rp_hw_profiles_py.rp_HPGetModelName()

def rp_HPGetModelEEPROM():
    return _rp_hw_profiles_py.rp_HPGetModelEEPROM()

def rp_HPGetModelETH_MAC_Address():
    return _rp_hw_profiles_py.rp_HPGetModelETH_MAC_Address()

def rp_HPGetZynqModel():
    return _rp_hw_profiles_py.rp_HPGetZynqModel()

def rp_HPGetZynqModelOrDefault():
    return _rp_hw_profiles_py.rp_HPGetZynqModelOrDefault()

def rp_HPGetBaseSpeedHz():
    return _rp_hw_profiles_py.rp_HPGetBaseSpeedHz()

def rp_HPGetBaseSpeedHzOrDefault():
    return _rp_hw_profiles_py.rp_HPGetBaseSpeedHzOrDefault()

def rp_HPGetHWADCFullScale():
    return _rp_hw_profiles_py.rp_HPGetHWADCFullScale()

def rp_HPGetHWADCFullScaleOrDefault():
    return _rp_hw_profiles_py.rp_HPGetHWADCFullScaleOrDefault()

def rp_HPGetHWDACFullScale():
    return _rp_hw_profiles_py.rp_HPGetHWDACFullScale()

def rp_HPGetHWDACFullScaleOrDefault():
    return _rp_hw_profiles_py.rp_HPGetHWDACFullScaleOrDefault()

def rp_HPGetBaseFastADCSpeedHz():
    return _rp_hw_profiles_py.rp_HPGetBaseFastADCSpeedHz()

def rp_HPGetBaseFastADCSpeedHzOrDefault():
    return _rp_hw_profiles_py.rp_HPGetBaseFastADCSpeedHzOrDefault()

def rp_HPGetSpectrumFastADCSpeedHz():
    return _rp_hw_profiles_py.rp_HPGetSpectrumFastADCSpeedHz()

def rp_HPGetSpectrumFastADCSpeedHzOrDefault():
    return _rp_hw_profiles_py.rp_HPGetSpectrumFastADCSpeedHzOrDefault()

def rp_HPGetFastADCChannelsCount():
    return _rp_hw_profiles_py.rp_HPGetFastADCChannelsCount()

def rp_HPGetFastADCChannelsCountOrDefault():
    return _rp_hw_profiles_py.rp_HPGetFastADCChannelsCountOrDefault()

def rp_HPGetFastADCIsSigned():
    return _rp_hw_profiles_py.rp_HPGetFastADCIsSigned()

def rp_HPGetFastADCIsSignedOrDefault():
    return _rp_hw_profiles_py.rp_HPGetFastADCIsSignedOrDefault()

def rp_HPGetFastADCBits():
    return _rp_hw_profiles_py.rp_HPGetFastADCBits()

def rp_HPGetFastADCBitsOrDefault():
    return _rp_hw_profiles_py.rp_HPGetFastADCBitsOrDefault()

def rp_HPGetFastADCGain(_in_channel, _in_mode):
    return _rp_hw_profiles_py.rp_HPGetFastADCGain(_in_channel, _in_mode)

def rp_HPGetFastADCGainOrDefault(channel, mode):
    return _rp_hw_profiles_py.rp_HPGetFastADCGainOrDefault(channel, mode)

def rp_HPIsFastDAC_Present():
    return _rp_hw_profiles_py.rp_HPIsFastDAC_Present()

def rp_HPIsFastDAC_PresentOrDefault():
    return _rp_hw_profiles_py.rp_HPIsFastDAC_PresentOrDefault()

def rp_HPGetFastDACIsTempProtection():
    return _rp_hw_profiles_py.rp_HPGetFastDACIsTempProtection()

def rp_HPGetFastDACIsTempProtectionOrDefault():
    return _rp_hw_profiles_py.rp_HPGetFastDACIsTempProtectionOrDefault()

def rp_HPGetBaseFastDACSpeedHz():
    return _rp_hw_profiles_py.rp_HPGetBaseFastDACSpeedHz()

def rp_HPGetBaseFastDACSpeedHzOrDefault():
    return _rp_hw_profiles_py.rp_HPGetBaseFastDACSpeedHzOrDefault()

def rp_HPGetFastDACChannelsCount():
    return _rp_hw_profiles_py.rp_HPGetFastDACChannelsCount()

def rp_HPGetFastDACChannelsCountOrDefault():
    return _rp_hw_profiles_py.rp_HPGetFastDACChannelsCountOrDefault()

def rp_HPGetFastDACIsSigned():
    return _rp_hw_profiles_py.rp_HPGetFastDACIsSigned()

def rp_HPGetFastDACIsSignedOrDefault():
    return _rp_hw_profiles_py.rp_HPGetFastDACIsSignedOrDefault()

def rp_HPGetFastDACBits():
    return _rp_hw_profiles_py.rp_HPGetFastDACBits()

def rp_HPGetFastDACBitsOrDefault():
    return _rp_hw_profiles_py.rp_HPGetFastDACBitsOrDefault()

def rp_HPGetFastDACGain(channel):
    return _rp_hw_profiles_py.rp_HPGetFastDACGain(channel)

def rp_HPGetFastDACGainOrDefault(channel):
    return _rp_hw_profiles_py.rp_HPGetFastDACGainOrDefault(channel)

def rp_HPGetFastADCIsLV_HV():
    return _rp_hw_profiles_py.rp_HPGetFastADCIsLV_HV()

def rp_HPGetFastADCIsLV_HVOrDefault():
    return _rp_hw_profiles_py.rp_HPGetFastADCIsLV_HVOrDefault()

def rp_HPGetFastADCIsAC_DC():
    return _rp_hw_profiles_py.rp_HPGetFastADCIsAC_DC()

def rp_HPGetFastADCIsAC_DCOrDefault():
    return _rp_hw_profiles_py.rp_HPGetFastADCIsAC_DCOrDefault()

def rp_HPGetFastADCIsFilterPresent():
    return _rp_hw_profiles_py.rp_HPGetFastADCIsFilterPresent()

def rp_HPGetFastADCIsFilterPresentOrDefault():
    return _rp_hw_profiles_py.rp_HPGetFastADCIsFilterPresentOrDefault()

def rp_HPGetSlowADCChannelsCount():
    return _rp_hw_profiles_py.rp_HPGetSlowADCChannelsCount()

def rp_HPGetSlowADCChannelsCountOrDefault():
    return _rp_hw_profiles_py.rp_HPGetSlowADCChannelsCountOrDefault()

def rp_HPGetSlowADCIsSigned(channel):
    return _rp_hw_profiles_py.rp_HPGetSlowADCIsSigned(channel)

def rp_HPGetSlowADCIsSignedOrDefault(channel):
    return _rp_hw_profiles_py.rp_HPGetSlowADCIsSignedOrDefault(channel)

def rp_HPGetSlowADCBits(channel):
    return _rp_hw_profiles_py.rp_HPGetSlowADCBits(channel)

def rp_HPGetSlowADCBitsOrDefault(channel):
    return _rp_hw_profiles_py.rp_HPGetSlowADCBitsOrDefault(channel)

def rp_HPGetSlowADCFullScale(channel):
    return _rp_hw_profiles_py.rp_HPGetSlowADCFullScale(channel)

def rp_HPGetSlowADCFullScaleOrDefault(channel):
    return _rp_hw_profiles_py.rp_HPGetSlowADCFullScaleOrDefault(channel)

def rp_HPGetSlowDACChannelsCount():
    return _rp_hw_profiles_py.rp_HPGetSlowDACChannelsCount()

def rp_HPGetSlowDACChannelsCountOrDefault():
    return _rp_hw_profiles_py.rp_HPGetSlowDACChannelsCountOrDefault()

def rp_HPGetSlowDACIsSigned(channel):
    return _rp_hw_profiles_py.rp_HPGetSlowDACIsSigned(channel)

def rp_HPGetSlowDACIsSignedOrDefault(channel):
    return _rp_hw_profiles_py.rp_HPGetSlowDACIsSignedOrDefault(channel)

def rp_HPGetSlowDACBits(channel):
    return _rp_hw_profiles_py.rp_HPGetSlowDACBits(channel)

def rp_HPGetSlowDACBitsOrDefault(channel):
    return _rp_hw_profiles_py.rp_HPGetSlowDACBitsOrDefault(channel)

def rp_HPGetSlowDACFullScale(channel):
    return _rp_hw_profiles_py.rp_HPGetSlowDACFullScale(channel)

def rp_HPGetSlowDACFullScaleOrDefault(channel):
    return _rp_hw_profiles_py.rp_HPGetSlowDACFullScaleOrDefault(channel)

def rp_HPGetIsGainDACx5():
    return _rp_hw_profiles_py.rp_HPGetIsGainDACx5()

def rp_HPGetIsGainDACx5OrDefault():
    return _rp_hw_profiles_py.rp_HPGetIsGainDACx5OrDefault()

def rp_HPGetIsCalibrationLogicPresent():
    return _rp_hw_profiles_py.rp_HPGetIsCalibrationLogicPresent()

def rp_HPGetIsCalibrationLogicPresentOrDefault():
    return _rp_hw_profiles_py.rp_HPGetIsCalibrationLogicPresentOrDefault()

def rp_HPGetIsPLLControlEnable():
    return _rp_hw_profiles_py.rp_HPGetIsPLLControlEnable()

def rp_HPGetIsPLLControlEnableOrDefault():
    return _rp_hw_profiles_py.rp_HPGetIsPLLControlEnableOrDefault()

def rp_HPGetIsAttenuatorControllerPresent():
    return _rp_hw_profiles_py.rp_HPGetIsAttenuatorControllerPresent()

def rp_HPGetIsAttenuatorControllerPresentOrDefault():
    return _rp_hw_profiles_py.rp_HPGetIsAttenuatorControllerPresentOrDefault()

def rp_HPGetIsExternalTriggerLevelPresent():
    return _rp_hw_profiles_py.rp_HPGetIsExternalTriggerLevelPresent()

def rp_HPGetIsExternalTriggerLevelPresentOrDefault():
    return _rp_hw_profiles_py.rp_HPGetIsExternalTriggerLevelPresentOrDefault()

def rp_HPGetIsExternalTriggerFullScale():
    return _rp_hw_profiles_py.rp_HPGetIsExternalTriggerFullScale()

def rp_HPGetIsExternalTriggerFullScalePresentOrDefault():
    return _rp_hw_profiles_py.rp_HPGetIsExternalTriggerFullScalePresentOrDefault()

def rp_HPGetIsDaisyChainClockAvailable():
    return _rp_hw_profiles_py.rp_HPGetIsDaisyChainClockAvailable()

def rp_HPGetIsDaisyChainClockAvailableOrDefault():
    return _rp_hw_profiles_py.rp_HPGetIsDaisyChainClockAvailableOrDefault()

def rp_HPGetIsDMAinv0_94():
    return _rp_hw_profiles_py.rp_HPGetIsDMAinv0_94()

def rp_HPGetIsDMAinv0_94OrDefault():
    return _rp_hw_profiles_py.rp_HPGetIsDMAinv0_94OrDefault()

def rp_HPPrint():
    return _rp_hw_profiles_py.rp_HPPrint()

def rp_HPPrintAll():
    return _rp_hw_profiles_py.rp_HPPrintAll()


